# Generated by Django 4.1.6 on 2023-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
