# Generated by Django 4.1.7 on 2023-02-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
